language: java

env:
    global:
        - JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64/

build:
    cache: false


    pre_ci_boot:
        image_name: zephyrprojectrtos/ci
        image_tag: v0.9.1
        pull: true
        options: "-e HOME=/home/buildslave --privileged=true --tty --net=bridge --user buildslave"

    ci:
      - sudo apt-get update || true
      - sudo apt install openjdk-11-jdk maven
      - >
        if [ "$IS_PULL_REQUEST" = "true" ]; then
          git rebase origin/${PULL_REQUEST_BASE_BRANCH}
        fi;
        mvn clean package

branches:
  only:
    - master
